/*
 * wavetable.c — Wavetable initialization.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * The sine table is computed at runtime via libm sin() rather than
 * embedded as a precomputed array. This keeps the source small and
 * avoids needing a code-generation step in the build. The cost is a
 * one-time initialization at lfe_init() — about 512 floating-point
 * sin() calls. On NDS this uses newlib's soft-float sin which is slow,
 * but it's a one-shot at startup so the user-visible cost is invisible.
 *
 * If startup time ever becomes a concern, we can replace this with a
 * precomputed const array generated by a separate utility.
 */

#include "wavetable.h"

#include <math.h>
#include <stdbool.h>

q15_t lfe_wt_sine[LFE_WT_SIZE];

static bool g_wt_inited = false;

void lfe_wavetable_init(void)
{
    if (g_wt_inited)
        return;

    /* sin(2*pi*i/N) scaled to Q15. We use the float computation only at
     * init time; the runtime path reads the integer table. */
    const double two_pi_over_n = (2.0 * 3.14159265358979323846) / (double)LFE_WT_SIZE;

    for (uint32_t i = 0; i < LFE_WT_SIZE; i++) {
        double v = sin((double)i * two_pi_over_n);
        /* Scale to Q15. Use 32767 (not 32768) so +1.0 maps cleanly. */
        int32_t s = (int32_t)(v * 32767.0);
        if (s >  32767) s =  32767;
        if (s < -32767) s = -32767;
        lfe_wt_sine[i] = (q15_t)s;
    }

    g_wt_inited = true;
}
